### PR TITLE
Updated to Forge 7.8.0.684

### PR DESCRIPTION
**Pull request by odininon**

### CODE REVIEW

**Comment by agaricusb** [comment]
Hm does this work? (mvn initialize -P -built) Since Mojang changed the location of the Minecraft jar downloads..

**Comment by odininon** [comment]
Doesn't look like they changed the location of the downloads. This initializes fine, unless I am mistaken and am using a cache from somewhere weird.

**Comment by agaricusb** [comment]
Ah you're right, http://assets.minecraft.net/1_5_2/minecraft_server.jar used to return forbidden, had to use the new URL http://s3.amazonaws.com/Minecraft.Download/versions/1.5.2/minecraft_server.1.5.2.jar instead, but it looks like Mojang restored the original location.

Holding off merging though until I can release a (non-shapshot) final version for 1.5.1.

**Comment by odininon** [comment]
Okay, wasn't sure what the procedure was on that, I figured since 684 was recommended now I would update it for you.

**Comment by odininon** [comment]
Is this version still valid or do you want me to push another version to the appropriate branch?

**Comment by agaricusb** [comment]
Just merged this in https://github.com/agaricusb/ForgeMod/commit/94f3f53891e20e14970b51b0f699f458b41fe2cb
thanks again :)

**Comment by odininon** [comment]
Always glad to help, looked like you were busy. :)

**Pull request closed without merging**
